root: true
env:
  browser: false
  node: false

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  project: tsconfig.json

plugins:
  - '@typescript-eslint'
  - import
  - standard

extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - standard

rules:
  # I actually like standard/standard, but:
  indent:
    - error
    - tab
    - SwitchCase: 0
      FunctionExpression:
        parameters: first
      FunctionDeclaration:
        parameters: first
      CallExpression:
        arguments: first
      flatTernaryExpressions: true
  no-tabs:
    - error
    - allowIndentationTabs: true
  max-len:
    - error
    - code: 80
      tabWidth: 4
      ignoreComments: true
      ignoreUrls: true
  comma-dangle:
    - error
    - always-multiline
  new-parens:
    - error
    - never
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: true
  no-unused-vars: &unused_vars
    - error
    - vars: all
      varsIgnorePattern: '^___'
      args: all
      argsIgnorePattern: '^_+$'
      caughtErrors: all
  '@typescript-eslint/no-unused-vars': *unused_vars
  operator-linebreak:
    - error
    - before
  no-undef:
    - error
  # member-delimiter-style:
  #   - error
  #   - multiline:
  #       delimiter: none
  #     singleline:
  #       delimiter: comma
  #       requireLast: true
