root: true
env:
  node: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  project: tsconfig.json

plugins:
  - '@typescript-eslint'
  - import
  - standard

extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - standard

rules:
  # I actually like standard/standard, but:
  indent:
    - error
    - tab
    - SwitchCase: 0
  no-tabs:
    - error
    - allowIndentationTabs: true
  max-len:
    - error
    - code: 80
      tabWidth: 4
      ignoreComments: true
      ignoreUrls: true
  comma-dangle:
    - error
    - always-multiline
  new-parens:
    - error
    - never
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_+$'
      args: all
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: true
  # member-delimiter-style:
  #   - error
  #   - multiline:
  #       delimiter: none
  #     singleline:
  #       delimiter: comma
  #       requireLast: true
