version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm ci && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - dist

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - run: |
          git checkout --orphan gh-pages &&
          git reset
          git add dist &&
          git clean -df &&
          git checkout -- .
      - run: mv dist/* . && rm -d dist
      - run: |
          git config user.email "bot@xnu.kr" &&
          git config user.name "Xnuk Bot"
      - run: git add --all && git commit -m '[ci skip]'
      - run: git push --set-upstream origin HEAD --force-with-lease

workflows:
  version: 2
  dep:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
