name: Bulldozer

on:
  push:
    branches-ignore:
    - gh-pages
    paths-ignore:
    - pnpm-lock.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: corepack enable
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm

    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
      env:
        NODE_ENV: production

    - uses: actions/upload-artifact@v3
      with:
        name: index.min.html
        path: dist/index.html

  deploy:
    needs:
    - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: gh-pages

    - run: >
        rm -rf * &&
        echo qr.xnu.kr > CNAME

    - uses: actions/download-artifact@v3
      with:
        name: index.min.html
        path: .

    - name: pushu
      run: |
        git config user.email action@github.com
        git config user.name 'Ship it parrot'
        git add --all
        git commit -m '[deployed] commit ${{ github.sha }}' || true
        git push origin HEAD
