name: Bulldozer

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  is-master:
    runs-on: ubuntu-latest
    steps:
    - run: >
        test "$GITHUB_REF" = "refs/heads/master"

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 13.x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm ci
      env:
        CI: true

    - name: npm build
      run: npm run build
      env:
        CI: true

    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist


  deploy:
    needs:
    - build
    - is-master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: gh-pages

    - run: >
        rm -rf * &&
        echo qr.xnu.kr > CNAME

    - uses: actions/download-artifact@v1
      with:
        name: dist
        path: .

    - name: pushu
      run: >
        git config user.email action@github.com &&
        git config user.name 'Ship it parrot' &&
        git add --all && git commit -m '[ci skip]' &&
        git push origin HEAD
