name: Bulldozer

on:
  push:
    branches-ignore:
    - gh-pages
    paths-ignore:
    - pnpm-lock.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: /home/runner/.npm/global-packages

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-v1

    - uses: actions/cache@v1
      id: pnpm-bin
      with:
        path: ${{ env.NPM_CONFIG_PREFIX }}
        key: ${{ runner.os }}-pnpm-bin-v1

    - name: Installing pnpm
      run: npx pnpm add -g pnpm
      if: steps.pnpm-bin.outputs.cache-hit != 'true'

    - name: pnpm install
      run: >
        export PATH=$NPM_CONFIG_PREFIX/bin:$PATH &&
        pnpm install

    - name: build
      run: >
        export PATH=$NPM_CONFIG_PREFIX/bin:$PATH &&
        pnpm run build
      env:
        NODE_ENV: production

    - uses: actions/upload-artifact@v1
      with:
        name: index.min.html
        path: dist/index.html

  deploy:
    needs:
    - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: gh-pages

    - run: >
        rm -rf * &&
        echo qr.xnu.kr > CNAME

    - uses: actions/download-artifact@v1
      with:
        name: index.min.html
        path: .

    - name: pushu
      run: |
        git config user.email action@github.com
        git config user.name 'Ship it parrot'
        git add --all
        git commit -m '[deployed] commit ${{ github.sha }}' || true
        git push origin HEAD
