name: Bulldozer

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: npm ci && npm run build
      env:
        CI: true

    - name: pushu
      run: |
        git checkout --orphan gh-pages &&
        git reset &&
        git add dist &&
        git clean -df &&
        git checkout -- . &&
        mv dist/* . &&
        rm -d dist &&
        
        git remote rm origin
        git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git fetch

        git config user.email ${GITHUB_ACTOR}@users.noreply.github.com &&
        git config user.name ${GITHUB_ACTOR} &&
        git add --all && git commit -m '[ci skip]' &&
        git push origin gh-pages --force-with-lease
