name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: npm ci && npm run build
      env:
        CI: true

    - name: pushu
      run: |
        git checkout --orphan gh-pages &&
        git reset &&
        git add dist &&
        git clean -df &&
        git checkout -- . &&
        mv dist/* . &&
        rm -d dist &&

        git config user.email xnuk@users.noreply.github.com &&
        git config user.name xnuk &&
        git add --all && git commit -m '[ci skip]' &&
        git push --set-upstream origin HEAD --force-with-lease
